const totalRuntime=122;
const raw=[
[1,'Research workflows',0,10,'You are a scientist who prepares samples, performs measurements, or runs simulations.','Split screen: spin-coating and sample handling, XPS measurement, molecular modelling and simulation.','Laboratory + simulation office',['Researcher','Lab technician'],'mixed'],
[2,'A growing amount of data',10,9,'Along the way, your data starts to accumulate: files from different instruments and software, stored in different formats and locations.','Running instruments in the lab. A researcher opens files from different instruments and software.','Characterisation lab',['Researcher'],'camera'],
[3,'Organization gets difficult',19,7,'Keeping your data organized and well-documented quickly becomes overwhelming.','Victoria speaks directly to camera.','CSMB Foyer',['Victoria Coors'],'camera'],
[4,'One platform for research data',26,9,'This is where NOMAD Central comes in: one platform to organize, manage, publish, and reuse your research data.','Victoria speaks directly to camera.','CSMB Foyer',['Victoria Coors'],'camera'],
[5,'Secure browser access',35,10,'It is free, with nothing to install and no programming required. Simply open NOMAD in your browser, create a new account or sign in securely using your institutional credentials.','Researcher on the laptop in an office, opens NOMAD in a browser and creates a new account using AAI.','Office 1.106',['Dea'],'camera'],
[6,'Projects and collaboration',45,8,'Organize your work into projects, add files, invite colleagues, and share access.','Create a project, add files, invite colleagues and share access.','NOMAD Platform',['None'],'screen'],
[7,'Structured scientific entries',53,12,'Upload your measurement or simulation output files. NOMAD recognizes many scientific file formats and automatically extracts the data and metadata into structured entries that you can easily search, analyze, and visualize.','Screen recording followed by camera footage of a scientist exploring the structured data.','NOMAD platform + Office 1.106',['Dea'],'mixed'],
[8,'Integrated analysis',65,8,'Analyze your data directly in NOMAD, using integrated tools without having to move your data to another platform.','Open integrated analysis tools and analyze an entry without leaving NOMAD.','NOMAD Platform',['None'],'screen'],
[9,'Publish with a DOI',73,8,'Publish your datasets with a DOI so they can be cited and reused by others.','Screen recording of DOI publication followed by camera footage of the data availability statement.','NOMAD platform + Office 1.106',['Dea'],'mixed'],
[10,'FAIR research data',81,6,'With NOMAD, your research data become FAIR: Findable, Accessible, Interoperable, and Reusable.','Victoria speaks to camera. FAIR terms appear as restrained on-screen typography.','CSMB Foyer',['Victoria Coors'],'camera'],
[11,'Millions of reusable entries',87,9,'Millions of FAIR materials data entries are already available on NOMAD and ready for re-use. You can explore this wealth of data using NOMAD’s web interface or programmatically with its comprehensive API.','Camera footage of Victoria followed by a scientist exploring NOMAD data.','CSMB Foyer + Office 1.106',['Victoria Coors','Dea'],'mixed'],
[12,'Search and domain apps',96,8,'Search by materials, properties, or methods. Or use NOMAD’s domain-specific apps, with interfaces tailored to research areas such as solar cells and catalysis.','Search by material, property or method, then open solar-cell and catalysis apps.','NOMAD Platform',['None'],'screen'],
[13,'Data ready for AI',104,10,'By transforming raw files into standardized, machine-readable data, NOMAD makes materials data ready for AI and data-driven research - from training models and discovering patterns to predicting properties and identifying new materials.','Victoria speaks directly to camera.','CSMB Foyer',['Victoria Coors'],'camera'],
[14,'Join the community',114,4,'For more information visit our website and join us on Discord.','Victoria speaks to camera. End card with website and community callout.','CSMB Foyer',['Victoria Coors'],'camera']];
const scenes=raw.map(([id,title,start,duration,sentence,footage,location,actors,type])=>({id,title,start,duration,sentence,footage,location,actors,type}));
const scene1Shots=[
 {id:'1.1',image:'../public/central-scene-01-shot-01-spin-coating.png',title:'Spin-coating and sample handling',description:'Scientist drops a colorful solution onto a spinning sample on a spin coater. Solution will be provided by Martin.',location:'CSMB Chemistry lab',actors:'Martin Bogner will contact someone - TBC'},
 {id:'1.2',image:'../public/central-scene-01-shot-02-xps-measurement.png',title:'XPS measurement',description:'Scientist on an XPS system, touching knobs and moving manipulator',location:'CSMB Joint Lab',actors:'Lennart Frohloff'},
 {id:'1.3',image:'../public/central-scene-01-shot-03-simulation.png',title:'Molecular simulations',description:'Scientist models molecules and runs simulations.',location:'Office 1.106',actors:'Martin Kuban'}
];
const scene2Shots=[
 {id:'2.1',image:'../public/central-scene-02-shot-01-lab-instruments.png',title:'Array of running instruments',description:'Inside the lab: an array of running instruments including a PES(N.Koch), Electron Microscope(C. T. Koch), Laser Microscope (Emil-list), AFM (Martin Bogner), Raman Spectroscopy setup (Nicolai).',location:'CSMB labs',actors:'No featured actor',note:'Confrimed except of Raman spectroscopy setup'},
 {id:'2.2',image:'../public/central-scene-02-shot-02-file-formats.png',title:'Files in different formats',description:'In the office: a scientist plugs a flash drive into a PC and opens a folder with various file in different formats.',location:'Office 1.106',actors:'Dea',note:'AM to prepare the files'}
];
const scene7Shots=[
 {id:'7.1',label:'SCREEN RECORDING',images:['../public/central-scene-07-shot-01-project-files.png','../public/central-scene-07-shot-02-xps-visualization.png'],title:'NOMAD screen recording',description:'One continuous screen recording represented by two moments: uploading raw files to a project and viewing the automatically extracted and visualized scientific data.',location:'NOMAD platform',actors:'None'},
 {id:'7.2',label:'CAMERA FOOTAGE',image:'../public/central-scene-07-shot-03-scientist-exploring.png',title:'Scientist exploring the data',description:'Researcher reviews the structured XPS entry and explores its instrument metadata in NOMAD.',location:'Office 1.106',actors:'Dea'}
];
const scene9Shots=[
 {id:'9.1',label:'SCREEN RECORDING',image:'../public/central-scene-09-shot-01-doi-publishing.png',title:'Assign the DOI',description:'Screen recording of publishing the NOMAD dataset and assigning its DOI. This process occupies the first half of the scene.',location:'NOMAD platform',actors:'None'},
 {id:'9.2',label:'CAMERA FOOTAGE',image:'../public/central-scene-09-shot-02-data-availability.png',title:'Add the data availability statement',description:'Dea edits the manuscript and adds a data availability statement linking readers to the dataset on NOMAD using its DOI.',location:'Office 1.106',actors:'Dea'}
];
const scene11Shots=[
 {id:'11.1',label:'CAMERA FOOTAGE',image:'../public/speaker-victoria-coors-lab.png',title:'Victoria introduces reusable NOMAD data',description:'Victoria speaks directly to camera for the first half of the scene.',location:'CSMB Foyer',actors:'Victoria Coors'},
 {id:'11.2',label:'CAMERA FOOTAGE',image:'../public/central-scene-11-explore-app.png',title:'Explore data using filters',description:'Researcher navigates to the Explore app and demonstrates the available filters and entry results.',location:'Office 1.106',actors:'Julian or Siamak'}
];
const shotArrays={0:scene1Shots,1:scene2Shots,6:scene7Shots,8:scene9Shots,10:scene11Shots};
let active=0,time=0,playing=false,timer=null;const $=id=>document.getElementById(id),fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function renderList(){const q=$('search').value.toLowerCase(),visible=scenes.filter(s=>`${s.title} ${s.sentence} ${s.location}`.toLowerCase().includes(q));$('count').textContent=visible.length;$('sentence-list').innerHTML=visible.map(s=>`<button data-id="${s.id}" class="sentence-item ${s.id===scenes[active].id?'is-active':''}"><span class="scene-number">${String(s.id).padStart(2,'0')}</span><span class="sentence-copy"><strong>${s.title}</strong><span>${s.sentence}</span><small>${fmt(s.start)} – ${fmt(s.start+s.duration)}</small></span></button>`).join('')||'<div class="empty">No matching sentences</div>';document.querySelectorAll('.sentence-item').forEach(b=>b.onclick=()=>select(+b.dataset.id-1))}
function render(){const s=scenes[active],isFirst=active===0;$('timecode').textContent=fmt(time);$('playhead').style.left=`${(time/totalRuntime)*100}%`;$('scrubber').value=time;$('scene-counter').textContent=`SCENE ${String(s.id).padStart(2,'0')} OF ${scenes.length}`;$('duration').textContent=`${s.duration} SEC`;$('preview').className=`preview preview-${s.type} ${isFirst?'preview-with-triangles':''}`;$('shot-label').textContent=`FOOTAGE ${String(s.id).padStart(2,'0')} · ${s.type==='screen'?'SCREEN RECORDING':s.type==='mixed'?'MIXED MEDIA':'CAMERA FOOTAGE'}`;$('normal-preview').hidden=isFirst;$('triangle-preview').hidden=!isFirst;$('scene1-shot-list').hidden=!isFirst;$('standard-footage').hidden=isFirst;if(isFirst){$('triangle-preview').innerHTML=scene1Shots.map(shot=>`<figure class="triangle-shot"><img src="${shot.image}" alt="Representative view of ${shot.title}"><figcaption><b>FOOTAGE ${shot.id}</b><span>${shot.title}</span></figcaption></figure>`).join('');$('scene1-shot-list').innerHTML=scene1Shots.map(shot=>`<article class="shot-detail"><div class="shot-detail-number">${shot.id}</div><div><strong>${shot.title}</strong><p>${shot.description}</p><dl><div><dt>LOCATION</dt><dd>${shot.location}</dd></div><div><dt>ACTORS</dt><dd>${shot.actors}</dd></div></dl></div></article>`).join('')}else{$('preview-location').textContent=s.location;$('footage').textContent=s.footage;$('location').textContent=s.location;$('actors').innerHTML=s.actors.map(a=>`<em>${a}</em>`).join('')}$('preview-time').textContent=`${fmt(s.start)} – ${fmt(s.start+s.duration)}`;$('quote').textContent=`“${s.sentence}”`;$('detail-duration').textContent=`${s.duration} seconds`;$('previous').disabled=active===0;$('next').disabled=active===scenes.length-1;renderList();renderTrack()}
function renderTrack(){$('track').innerHTML=scenes.map((s,i)=>`<button data-index="${i}" aria-label="Scene ${s.id}: ${s.title}" class="clip clip-${s.type} ${i===active?'is-active':''}" style="width:${s.duration/1.2}%"><span>${s.id}</span></button>`).join('');$('scene-dots').innerHTML=scenes.map((s,i)=>`<button data-index="${i}" aria-label="Go to scene ${s.id}" class="${i===active?'active':''}"></button>`).join('');document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>select(+b.dataset.index))}
const baseRender=render;render=function(){baseRender();const isVictoria=scenes[active].actors.includes('Victoria Coors'),sceneImage=active===4?'../public/central-scene-05-nomad-login.png':active===5?'../public/central-scene-06-new-project.png':isVictoria?'../public/speaker-victoria-coors-lab.png':null,isShotArray=active in shotArrays,shots=shotArrays[active],isScene7=active===6;$('victoria-preview').hidden=!sceneImage;if(sceneImage)$('victoria-preview').src=sceneImage;$('victoria-preview').alt=active===4?'Dea opening NOMAD on a laptop':active===5?'NOMAD New Project screen with file and collaborator controls':'Illustrative camera framing of Victoria in the laboratory';$('normal-preview').hidden=!!sceneImage||isShotArray;$('triangle-preview').hidden=!isShotArray;$('scene1-shot-list').hidden=!isShotArray;$('standard-footage').hidden=isShotArray;$('preview').classList.toggle('scene-seven-preview',isScene7);$('triangle-preview').className=`triangle-preview ${(active===1||isScene7)?'two-shot-array':''} ${isScene7?'scene-seven-array':''}`;if(isShotArray){$('triangle-preview').innerHTML=shots.map(shot=>`<figure class="triangle-shot">${shot.images?`<div class="representative-pair">${shot.images.map((image,index)=>`<img src="${image}" alt="Representative screen-recording moment ${index+1}">`).join('')}</div>`:`<img src="${shot.image}" alt="Representative view of ${shot.title}">`}<figcaption><b>FOOTAGE ${shot.id}: ${shot.label||'CAMERA FOOTAGE'}</b><span>${shot.title}</span></figcaption></figure>`).join('');$('scene1-shot-list').innerHTML=shots.map(shot=>`<article class="shot-detail"><div class="shot-detail-number">${shot.id}</div><div><strong>${shot.title}</strong><p>${shot.description}</p><dl><div><dt>LOCATION</dt><dd>${shot.location}</dd></div><div><dt>ACTORS</dt><dd>${shot.actors}</dd></div>${shot.note?`<div class="shot-note"><dt>PRODUCTION</dt><dd>${shot.note}</dd></div>`:''}</dl></div></article>`).join('')}$('scene-counter').textContent=`SCENE ${String(scenes[active].id).padStart(2,'0')} OF ${scenes.length}`;$('next').disabled=active===scenes.length-1};
const sceneMediaRender=render;render=function(){sceneMediaRender();if(active===7){$('victoria-preview').src='../public/central-scene-08-north-tools.png';$('victoria-preview').alt='NOMAD Remote Tools Hub showing integrated analysis tools';$('victoria-preview').hidden=false;$('normal-preview').hidden=true}};
const scene9Render=render;render=function(){scene9Render();const isScene9=active===8;$('shot-label').hidden=isScene9;if(isScene9)$('triangle-preview').classList.add('two-shot-array')};
const scene11Render=render;render=function(){scene11Render();const isScene11=active===10;if(isScene11){$('shot-label').hidden=true;$('triangle-preview').classList.add('two-shot-array')}};
const scene12Render=render;render=function(){scene12Render();if(active===11){$('victoria-preview').src='../public/central-scene-12-solar-cell-app.png';$('victoria-preview').alt='NOMAD perovskite solar-cell database with filters, charts and results';$('victoria-preview').hidden=false;$('normal-preview').hidden=true}};
const finalSceneRender=render;render=function(){finalSceneRender();const isFinal=active===scenes.length-1;$('end-card').hidden=!isFinal;$('preview').classList.toggle('final-scene-preview',isFinal);if(isFinal){$('victoria-preview').hidden=true;$('normal-preview').hidden=true;$('triangle-preview').hidden=true}};
function select(i){active=Math.max(0,Math.min(scenes.length-1,i));time=scenes[active].start;render()}function seek(value){time=value;active=Math.max(0,scenes.findLastIndex(s=>s.start<=time));render()}$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Ⅱ':'▶';if(playing){timer=setInterval(()=>{time=Math.min(totalRuntime,time+.1);active=Math.max(0,scenes.findLastIndex(s=>s.start<=time));render();if(time>=totalRuntime)$('play').click()},100)}else clearInterval(timer)};$('scrubber').oninput=e=>seek(+e.target.value);$('previous').onclick=()=>select(active-1);$('next').onclick=()=>select(active+1);$('search').oninput=renderList;$('toggle').onclick=()=>{const open=$('toggle').getAttribute('aria-checked')==='true';$('toggle').setAttribute('aria-checked',String(!open));$('details').hidden=open;$('reopen').hidden=!open};$('reopen').onclick=()=>$('toggle').click();render();
