const raw=[
[1,'Research workflows',0,10,'You are a scientist who prepares samples, performs measurements, or runs simulations.','Split screen: spin-coating and sample handling, XPS measurement, molecular modelling and simulation.','Laboratory + simulation office',['Researcher','Lab technician'],'mixed'],
[2,'A growing amount of data',10,9,'Along the way, you produce a growing amount of data: files from different instruments and software, in different formats, stored in different places.','Running instruments in the lab. A researcher opens files from different instruments and software.','Characterisation lab',['Researcher'],'camera'],
[3,'Organization gets difficult',19,7,'Keeping your data organized and well-documented can quickly become overwhelming.','Victoria speaks directly to camera. Medium shot with a clean scientific background.','NOMAD office',['Victoria Coors'],'camera'],
[4,'One platform for research data',26,9,'This is where NOMAD Central comes in. One platform for managing your research data from creation to publication and reuse.','Victoria speaks to camera, followed by a transition into the NOMAD Central interface.','NOMAD office',['Victoria Coors'],'mixed'],
[5,'Secure browser access',35,10,'It is free, with nothing to install and no programming required. Simply open NOMAD in your browser and sign in securely using your institutional account or another supported login.','Open NOMAD in a browser and demonstrate the secure sign-in options.','Screen recording',['Screen only'],'screen'],
[6,'Projects and collaboration',45,8,'Organize your work into projects, add files, invite colleagues, and share access.','Create a project, add files, invite colleagues and share access.','Screen recording',['Screen only'],'screen'],
[7,'Structured scientific entries',53,12,'Upload your raw measurement or simulation output files. NOMAD recognizes many scientific file formats and automatically extracts the data and their metadata into structured entries that can be easily visualized.','Upload raw measurement and simulation files, then show automatic extraction and a visualized structured entry.','Screen recording',['Screen only'],'screen'],
[8,'Integrated analysis',65,8,'Analyze your data directly in NOMAD, using integrated tools without having to move your data to another platform.','Open integrated analysis tools and analyze an entry without leaving NOMAD.','Screen recording',['Screen only'],'screen'],
[9,'Publish with a DOI',73,8,'Finally, publish your datasets with a DOI so they can be referenced, cited, and reused by others.','Prepare a dataset for publication and assign a DOI.','Screen recording',['Screen only'],'screen'],
[10,'FAIR research data',81,6,'In this way, your research data become FAIR: Findable, Accessible, Interoperable, and Reusable.','Victoria speaks to camera. FAIR terms appear as restrained on-screen typography.','NOMAD office',['Victoria Coors'],'camera'],
[11,'Millions of reusable entries',87,9,'Millions of entries of FAIR materials data are already available on NOMAD and ready for re-use. You can explore and access them on the platform or even programmatically using our comprehensive API.','Explore NOMAD entries, then show an API access example.','NOMAD office + screen recording',['Victoria Coors'],'mixed'],
[12,'Search and domain apps',96,8,'Search for specific materials, properties, or methods. Or use our domain-specific apps such as solar cells and catalysis data.','Search by material, property or method, then open solar-cell and catalysis apps.','Screen recording',['Screen only'],'screen'],
[13,'Data ready for AI',104,10,'By transforming raw files into standardized, machine-readable data, NOMAD makes materials data ready for AI and data-driven research - from training models to discovering patterns and predicting new materials.','Connect raw files, standardized entries and examples of AI-driven materials research.','NOMAD office + screen recording',['Victoria Coors'],'mixed'],
[14,'Join the community',114,6,'For more information visit our website and join our community on Discord.','Victoria speaks to camera. End card with website and community callout.','NOMAD office',['Victoria Coors'],'camera']];
const scenes=raw.map(([id,title,start,duration,sentence,footage,location,actors,type])=>({id,title,start,duration,sentence,footage,location,actors,type}));
const scene1Shots=[
 {id:'1.1',image:'../public/footage-1-1.png',title:'Spin-coating and sample handling',description:'Scientist drops a colorful solution onto a spinning sample on a spin coater, then holds it with tweezers over a container.',location:'CSMB lab',actors:'People – TBC'},
 {id:'1.2',image:'../public/footage-1-2.png',title:'XPS measurement',description:'Scientist performs measurements on an XPS system.',location:'CSMB lab',actors:'People – TBC'},
 {id:'1.3',image:'../public/footage-1-3.png',title:'Molecular modelling and simulations',description:'Scientist models molecules and runs simulations.',location:'Office on Claudia’s floor',actors:'Martin Kuban, Joe'}
];
const scene2Shots=[
 {id:'2.1',image:'../public/footage-2-1.png',title:'Array of running instruments',description:'Inside the lab: an array of running instruments including a profilometer, electron microscope, conductivity setup, Raman spectroscopy and XPS.',location:'CSMB lab',actors:'No featured actor',note:'AM to check the instruments to film'},
 {id:'2.2',image:'../public/footage-2-2.png',title:'Files in different formats',description:'In the office: a scientist plugs a flash drive into a PC and opens multiple files in varying formats.',location:'Office 1.106',actors:'Dea',note:'AM to prepare the files'}
];
const scene7Shots=[
 {images:['../public/scene-7-project-files.png','../public/scene-7-xps-visualization.png'],title:'NOMAD screen recording',description:'One continuous screen recording represented by two moments: uploading raw files to a project and viewing the automatically extracted and visualized scientific data.',location:'NOMAD platform',actors:'Screen only'},
 {image:'../public/scene-7-scientist-exploring.png',title:'Scientist exploring the data',description:'A scientist reviews the structured XPS entry and explores its instrument metadata in NOMAD.',location:'Office',actors:'Scientist'}
];
const scene9Shots=[
 {id:'10A',image:'../public/scene-9-doi-publishing.png',title:'Assign the DOI',description:'Screen recording of publishing the NOMAD dataset and assigning its DOI. This process occupies the first half of the scene.',location:'Screen recording',actors:'Screen only'},
 {id:'10B',image:'../public/scene-9-data-availability.png',title:'Add the data availability statement',description:'The scientist edits the manuscript and adds a data availability statement linking readers to the dataset on NOMAD using its DOI.',location:'Office',actors:'Scientist'}
];
const scene11Shots=[
 {id:'11.1',image:'../public/victoria-lab-camera.png',title:'Victoria introduces reusable NOMAD data',description:'Victoria speaks directly to camera for the first half of the scene.',location:'NOMAD office',actors:'Victoria Coors'},
 {id:'11.2',image:'../public/scene-11-scientist-explore.png',title:'Explore data using filters',description:'A scientist navigates to the Explore app and demonstrates the available filters and entry results.',location:'Office',actors:'Scientist'}
];
const shotArrays={0:scene1Shots,1:scene2Shots,6:scene7Shots,8:scene9Shots,10:scene11Shots};
let active=0,time=0,playing=false,timer=null;const $=id=>document.getElementById(id),fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function renderList(){const q=$('search').value.toLowerCase(),visible=scenes.filter(s=>`${s.title} ${s.sentence} ${s.location}`.toLowerCase().includes(q));$('count').textContent=visible.length;$('sentence-list').innerHTML=visible.map(s=>`<button data-id="${s.id}" class="sentence-item ${s.id===scenes[active].id?'is-active':''}"><span class="scene-number">${String(s.id).padStart(2,'0')}</span><span class="sentence-copy"><strong>${s.title}</strong><span>${s.sentence}</span><small>${fmt(s.start)} – ${fmt(s.start+s.duration)}</small></span></button>`).join('')||'<div class="empty">No matching sentences</div>';document.querySelectorAll('.sentence-item').forEach(b=>b.onclick=()=>select(+b.dataset.id-1))}
function render(){const s=scenes[active],isFirst=active===0;$('timecode').textContent=fmt(time);$('playhead').style.left=`${time/1.2}%`;$('scrubber').value=time;$('scene-counter').textContent=`SCENE ${String(s.id).padStart(2,'0')} OF 15`;$('duration').textContent=`${s.duration} SEC`;$('preview').className=`preview preview-${s.type} ${isFirst?'preview-with-triangles':''}`;$('shot-label').textContent=s.type==='screen'?'▣  SCREEN RECORDING':s.type==='mixed'?'▣  MIXED FOOTAGE':'▣  CAMERA FOOTAGE';$('normal-preview').hidden=isFirst;$('triangle-preview').hidden=!isFirst;$('scene1-shot-list').hidden=!isFirst;$('standard-footage').hidden=isFirst;if(isFirst){$('triangle-preview').innerHTML=scene1Shots.map(shot=>`<figure class="triangle-shot"><img src="${shot.image}" alt="Representative view of ${shot.title}"><figcaption><b>FOOTAGE ${shot.id}</b><span>${shot.title}</span></figcaption></figure>`).join('');$('scene1-shot-list').innerHTML=scene1Shots.map(shot=>`<article class="shot-detail"><div class="shot-detail-number">${shot.id}</div><div><strong>${shot.title}</strong><p>${shot.description}</p><dl><div><dt>LOCATION</dt><dd>${shot.location}</dd></div><div><dt>ACTORS</dt><dd>${shot.actors}</dd></div></dl></div></article>`).join('')}else{$('preview-location').textContent=s.location;$('footage').textContent=s.footage;$('location').textContent=s.location;$('actors').innerHTML=s.actors.map(a=>`<em>${a}</em>`).join('')}$('preview-time').textContent=`${fmt(s.start)} – ${fmt(s.start+s.duration)}`;$('quote').textContent=`“${s.sentence}”`;$('detail-duration').textContent=`${s.duration} seconds`;$('previous').disabled=active===0;$('next').disabled=active===14;renderList();renderTrack()}
function renderTrack(){$('track').innerHTML=scenes.map((s,i)=>`<button data-index="${i}" aria-label="Scene ${s.id}: ${s.title}" class="clip clip-${s.type} ${i===active?'is-active':''}" style="width:${s.duration/1.2}%"><span>${s.id}</span></button>`).join('');$('scene-dots').innerHTML=scenes.map((s,i)=>`<button data-index="${i}" aria-label="Go to scene ${s.id}" class="${i===active?'active':''}"></button>`).join('');document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>select(+b.dataset.index))}
const baseRender=render;render=function(){baseRender();const isVictoria=scenes[active].actors.includes('Victoria Coors'),sceneImage=active===4?'/public/scene-5-nomad-login.png':active===5?'/public/scene-6-new-project.png':isVictoria?'/public/victoria-lab-camera.png':null,isShotArray=active in shotArrays,shots=shotArrays[active],isScene7=active===6;$('victoria-preview').hidden=!sceneImage;if(sceneImage)$('victoria-preview').src=sceneImage;$('victoria-preview').alt=active===4?'Scientist opening NOMAD on a laptop':active===5?'NOMAD New Project screen with file and collaborator controls':'Illustrative camera framing of Victoria in the laboratory';$('normal-preview').hidden=!!sceneImage||isShotArray;$('triangle-preview').hidden=!isShotArray;$('scene1-shot-list').hidden=!isShotArray;$('standard-footage').hidden=isShotArray;$('preview').classList.toggle('scene-seven-preview',isScene7);$('triangle-preview').className=`triangle-preview ${(active===1||isScene7)?'two-shot-array':''} ${isScene7?'scene-seven-array':''}`;if(isShotArray){$('triangle-preview').innerHTML=shots.map(shot=>`<figure class="triangle-shot">${shot.images?`<div class="representative-pair">${shot.images.map((image,index)=>`<img src="${image}" alt="Representative screen-recording moment ${index+1}">`).join('')}</div>`:`<img src="${shot.image}" alt="Representative view of ${shot.title}">`}${isScene7?'':`<figcaption><b>FOOTAGE ${shot.id}</b><span>${shot.title}</span></figcaption>`}</figure>`).join('');$('scene1-shot-list').innerHTML=shots.map(shot=>`<article class="shot-detail ${isScene7?'unnumbered':''}">${isScene7?'':`<div class="shot-detail-number">${shot.id}</div>`}<div><strong>${shot.title}</strong><p>${shot.description}</p><dl><div><dt>LOCATION</dt><dd>${shot.location}</dd></div><div><dt>ACTORS</dt><dd>${shot.actors}</dd></div>${shot.note?`<div class="shot-note"><dt>PRODUCTION</dt><dd>${shot.note}</dd></div>`:''}</dl></div></article>`).join('')}$('scene-counter').textContent=`SCENE ${String(scenes[active].id).padStart(2,'0')} OF ${scenes.length}`;$('next').disabled=active===scenes.length-1};
const sceneMediaRender=render;render=function(){sceneMediaRender();if(active===7){$('victoria-preview').src='../public/scene-8-north-tools.png';$('victoria-preview').alt='NOMAD Remote Tools Hub showing integrated analysis tools';$('victoria-preview').hidden=false;$('normal-preview').hidden=true}};
const scene9Render=render;render=function(){scene9Render();if(active===8)$('triangle-preview').classList.add('two-shot-array')};
const scene11Render=render;render=function(){scene11Render();if(active===10)$('triangle-preview').classList.add('two-shot-array')};
const scene12Render=render;render=function(){scene12Render();if(active===11){$('victoria-preview').src='../public/scene-12-solar-cell-app.png';$('victoria-preview').alt='NOMAD perovskite solar-cell database with filters, charts and results';$('victoria-preview').hidden=false;$('normal-preview').hidden=true}};
const finalSceneRender=render;render=function(){finalSceneRender();const isFinal=active===scenes.length-1;$('end-card').hidden=!isFinal;$('preview').classList.toggle('final-scene-preview',isFinal);if(isFinal){$('victoria-preview').hidden=true;$('normal-preview').hidden=true;$('triangle-preview').hidden=true}};
function select(i){active=Math.max(0,Math.min(scenes.length-1,i));time=scenes[active].start;render()}function seek(value){time=value;active=Math.max(0,scenes.findLastIndex(s=>s.start<=time));render()}$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Ⅱ':'▶';if(playing){timer=setInterval(()=>{time=Math.min(120,time+.1);active=Math.max(0,scenes.findLastIndex(s=>s.start<=time));render();if(time>=120)$('play').click()},100)}else clearInterval(timer)};$('scrubber').oninput=e=>seek(+e.target.value);$('previous').onclick=()=>select(active-1);$('next').onclick=()=>select(active+1);$('search').oninput=renderList;$('toggle').onclick=()=>{const open=$('toggle').getAttribute('aria-checked')==='true';$('toggle').setAttribute('aria-checked',String(!open));$('details').hidden=open;$('reopen').hidden=!open};$('reopen').onclick=()=>$('toggle').click();render();
