'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, Clapperboard, Clock3, MapPin, Pause, Play, Search, UserRound, Video } from 'lucide-react';

type Scene = { id:number; title:string; start:number; duration:number; sentence:string; footage:string; location:string; actors:string[]; type:'camera'|'screen'|'mixed' };
const scenes: Scene[] = [
  [1,'Research workflows',0,10,'You are a scientist who prepares samples, performs measurements, or runs simulations.','Split screen: spin-coating and sample handling, XPS measurement, molecular modelling and simulation.','Laboratory + simulation office',['Researcher','Lab technician'],'mixed'],
  [2,'Many data files',10,8,'Along the way, you produce growing amounts of data from different instruments and software, in different formats, stored in different places.','Running instruments in the lab. A researcher connects a flash drive and opens files in several formats.','Characterisation lab',['Researcher'],'camera'],
  [3,'Organization gets difficult',18,6,'Keeping your data organized and well documented can quickly become overwhelming.','Victoria speaks directly to camera. Medium shot with a clean scientific background.','NOMAD office',['Victoria Coors'],'camera'],
  [4,'One connected platform',24,8,'This is where NOMAD Central comes in: one platform for managing research data from creation to publication and reuse.','Victoria speaks to camera, followed by a short transition into the NOMAD Central interface.','NOMAD office',['Victoria Coors'],'mixed'],
  [5,'Start in the browser',32,7,'It is free, with nothing to install and no programming required. Simply open NOMAD Central in your browser and get started.','Researcher opens NOMAD Central in a browser and signs in.','Screen recording',['Screen only'],'screen'],
  [6,'Projects and collaboration',39,8,'Organize your work into projects, upload your data, and share it with your colleagues.','Create a project, upload data, invite colleagues and share access.','Screen recording',['Screen only'],'screen'],
  [7,'Structured samples',47,9,'Document your samples, their composition, and preparation conditions in a structured way. Connect them to substances and instruments.','Use the ELN to document a sample, its composition, preparation conditions, substances and instruments.','Screen recording',['Screen only'],'screen'],
  [8,'Automatic metadata',56,8,'Upload your data files. NOMAD recognizes many scientific formats and automatically extracts the data and metadata.','Upload scientific files. NOMAD recognizes the format, then parses the data and metadata.','Screen recording',['Screen only'],'screen'],
  [9,'Searchable entries',64,8,'Instead of just storing files, NOMAD turns them into structured entries that you can search, analyze, and visualize.','Open a NOMAD entry, check the overview and XPS spectra, then navigate through its fields.','Screen recording',['Screen only'],'screen'],
  [10,'Publish with a DOI',72,8,'Publish your projects with a DOI, so your research data can be referenced and cited by you and others.','Prepare a project for publication and assign a DOI.','Screen recording',['Screen only'],'screen'],
  [11,'FAIR research data',80,6,'In this way, your research data become FAIR: Findable, Accessible, Interoperable, and Reusable.','Victoria speaks to camera. FAIR terms appear as restrained on-screen typography.','NOMAD office',['Victoria Coors'],'camera'],
  [12,'Explore materials data',86,8,'You can also explore millions of materials-data entries in NOMAD and access them on the platform or programmatically.','Victoria speaks to camera, transitioning to NOMAD Explore views.','NOMAD office + screen recording',['Victoria Coors'],'mixed'],
  [13,'Search and domain apps',94,8,'Search for specific materials, properties, or methods, or use domain-specific apps such as solar cells and catalysis.','Search by material, property or method. Open domain apps for solar cells and catalysis.','Screen recording',['Screen only'],'screen'],
  [14,'The full data lifecycle',102,10,'From organizing your own research to publishing FAIR data, and from discovering existing results to using them for data-driven science, NOMAD Central connects the entire research data lifecycle.','Victoria speaks to camera. Brief visual callbacks connect project, publication and exploration steps.','NOMAD office',['Victoria Coors'],'camera'],
  [15,'Join the community',112,8,'For more information, visit our website and join our community on Discord.','Victoria speaks to camera. End card with website and community callout.','NOMAD office',['Victoria Coors'],'camera'],
].map(([id,title,start,duration,sentence,footage,location,actors,type]) => ({id,title,start,duration,sentence,footage,location,actors,type} as Scene));
const totalDuration = 120;
const formatTime = (seconds:number) => `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;

export default function Home() {
  const [activeIndex,setActiveIndex]=useState(0), [time,setTime]=useState(0), [playing,setPlaying]=useState(false), [detailsOpen,setDetailsOpen]=useState(true), [query,setQuery]=useState('');
  const listRef=useRef<HTMLDivElement>(null), active=scenes[activeIndex];
  const visibleScenes=useMemo(()=>scenes.filter(s=>`${s.title} ${s.sentence} ${s.location}`.toLowerCase().includes(query.toLowerCase())),[query]);
  useEffect(()=>{ if(!playing)return; const timer=window.setInterval(()=>setTime(current=>{const next=Math.min(current+.1,totalDuration), index=scenes.findLastIndex(s=>s.start<=next); if(index>=0)setActiveIndex(index); if(next>=totalDuration)setPlaying(false); return next}),100); return()=>clearInterval(timer)},[playing]);
  useEffect(()=>{listRef.current?.querySelector(`[data-scene="${active.id}"]`)?.scrollIntoView({block:'nearest',behavior:'smooth'})},[active.id]);
  const selectScene=(scene:Scene)=>{setActiveIndex(scenes.findIndex(s=>s.id===scene.id));setTime(scene.start)};
  const step=(direction:number)=>selectScene(scenes[Math.max(0,Math.min(scenes.length-1,activeIndex+direction))]);
  const seek=(value:number)=>{setTime(value);setActiveIndex(Math.max(0,scenes.findLastIndex(s=>s.start<=value)))};
  return <main className="app-shell">
    <header className="topbar"><div className="brand-mark"><span>N</span></div><div><div className="eyebrow">NOMAD VIDEO CAMPAIGN</div><h1>Central · Edit map</h1></div><div className="topbar-meta"><span>15 scenes</span><span className="dot"/><span>02:00</span></div></header>
    <section className="timeline" aria-label="Video timeline"><div className="timeline-header"><div className="transport"><button className="round-button" onClick={()=>setPlaying(!playing)} aria-label={playing?'Pause timeline':'Play timeline'}>{playing?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}</button><span className="timecode">{formatTime(time)}</span><span className="time-total">/ {formatTime(totalDuration)}</span></div><div className="legend"><span><i className="camera-key"/>Camera</span><span><i className="screen-key"/>Screen</span><span><i className="mixed-key"/>Mixed</span></div></div>
      <div className="ruler-row"><span>0:00</span><span>0:30</span><span>1:00</span><span>1:30</span><span>2:00</span></div><div className="track-wrap"><div className="track">{scenes.map((s,i)=><button key={s.id} aria-label={`Scene ${s.id}: ${s.title}`} className={`clip clip-${s.type} ${i===activeIndex?'is-active':''}`} style={{width:`${s.duration/totalDuration*100}%`}} onClick={()=>selectScene(s)}><span>{s.id}</span></button>)}</div><div className="playhead" style={{left:`${time/totalDuration*100}%`}}><span/></div><input className="scrubber" type="range" min="0" max={totalDuration} step=".1" value={time} onChange={e=>seek(Number(e.target.value))} aria-label="Seek video timeline"/></div>
    </section>
    <div className="workspace">
      <aside className="transcript-panel"><div className="panel-heading"><div><span className="section-label">TRANSCRIPT</span><h2>Sentences</h2></div><span className="count">{visibleScenes.length}</span></div><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search transcript"/></label><div className="sentence-list" ref={listRef}>{visibleScenes.map(s=><button key={s.id} data-scene={s.id} onClick={()=>selectScene(s)} className={`sentence-item ${s.id===active.id?'is-active':''}`}><span className="scene-number">{String(s.id).padStart(2,'0')}</span><span className="sentence-copy"><strong>{s.title}</strong><span>{s.sentence}</span><small>{formatTime(s.start)} – {formatTime(s.start+s.duration)}</small></span></button>)}</div></aside>
      <section className="scene-stage"><div className="stage-topline"><span>SCENE {String(active.id).padStart(2,'0')} OF {scenes.length}</span><span>{active.duration} SEC</span></div><div className={`preview preview-${active.type}`}><div className="frame-corners"/><div className="shot-label"><Video size={16}/>{active.type==='screen'?'SCREEN RECORDING':active.type==='mixed'?'MIXED FOOTAGE':'CAMERA FOOTAGE'}</div><div className="preview-content"><Clapperboard size={42} strokeWidth={1.3}/><span>Footage placeholder</span><small>{active.location}</small></div><div className="preview-time">{formatTime(active.start)} – {formatTime(active.start+active.duration)}</div></div><blockquote>“{active.sentence}”</blockquote><div className="scene-nav"><button onClick={()=>step(-1)} disabled={activeIndex===0}><ChevronLeft size={18}/>Previous</button><div className="scene-dots">{scenes.map((s,i)=><button key={s.id} aria-label={`Go to scene ${s.id}`} className={i===activeIndex?'active':''} onClick={()=>selectScene(s)}/>)}</div><button onClick={()=>step(1)} disabled={activeIndex===scenes.length-1}>Next<ChevronRight size={18}/></button></div></section>
      <aside className="details-panel"><div className="details-toggle-row"><div><span className="section-label">SCENE NOTES</span><h2>Footage details</h2></div><button role="switch" aria-checked={detailsOpen} className="switch" onClick={()=>setDetailsOpen(!detailsOpen)}><span/></button></div>{detailsOpen?<div className="details-content"><Detail icon={<Clapperboard size={18}/>} tone="amber" label="FOOTAGE"><p>{active.footage}</p></Detail><Detail icon={<MapPin size={18}/>} tone="blue" label="LOCATION"><p>{active.location}</p></Detail><Detail icon={<UserRound size={18}/>} tone="violet" label="ACTORS"><div className="actor-list">{active.actors.map(actor=><em key={actor}>{actor}</em>)}</div></Detail><Detail icon={<Clock3 size={18}/>} tone="mint" label="DURATION"><p>{active.duration} seconds</p></Detail><div className="production-note"><span>PRODUCTION NOTE</span><p>Use this panel during planning and editing to verify the shot against each spoken sentence.</p></div></div>:<button className="reopen" onClick={()=>setDetailsOpen(true)}>Show footage, location and actors</button>}</aside>
    </div>
  </main>;
}

function Detail({icon,tone,label,children}:{icon:React.ReactNode;tone:string;label:string;children:React.ReactNode}){return <div className="detail-block"><div className={`detail-icon ${tone}`}>{icon}</div><div><span>{label}</span>{children}</div></div>}
